name: unity-ci

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: EditMode Tests (2022.3.39f1)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.39f1
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  # Build job can be enabled after license setup
  # build-windows:
  #   name: Build Windows Player (2022.3.39f1)
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: game-ci/unity-builder@v4
  #       with:
  #         unityVersion: 2022.3.39f1
  #         targetPlatform: StandaloneWindows64
  #       env:
  #         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
